### ISSUE TITLE
Server Crash ; Ticking Entity (when using ANY mob that isn't minecraft or Animania)

### ISSUE THREAD

**Issue by Ski-z** [a3626a/HungryAnimals-1.8#52]
---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// Shall we play a game?

Time: 2024-07-09 23:58:44 MDT
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at oortcloud.hungryanimals.entities.event.EntityEventHandler.updateTaming(EntityEventHandler.java:301)
    at oortcloud.hungryanimals.entities.event.EntityEventHandler.onLivingEntityUpdate(EntityEventHandler.java:133)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1975_EntityEventHandler_onLivingEntityUpdate_LivingUpdateEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(MixinForgeHooks.java:581)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2095)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:750)

(MixinBooter) Mixins in Stacktrace:
    net/minecraftforge/common/ForgeHooks:
        youyihj.zenutils.impl.mixin.vanilla.MixinForgeHooks (mixins.zenutils.vanilla.json) [unknown-location]
    net/minecraft/entity/EntityLiving:
        mod.acgaming.universaltweaks.tweaks.entities.despawning.mixin.EntityLivingAccessor (mixins.tweaks.entities.despawning.json) [unknown-location]
        net.smileycorp.hordes.mixin.MixinEntityLiving (mixins.hordes.json) [unknown-location]
    net/minecraft/entity/EntityLivingBase:
        mod.acgaming.universaltweaks.tweaks.misc.armorcurve.mixin.UTValueUpdateMixin (mixins.tweaks.misc.armorcurve.json) [unknown-location]
        com.github.mikn.lava_walker.asm.mixin.EntityLivingBaseMixin (lava_walker.mixins.json) [unknown-location]
        mod.acgaming.universaltweaks.bugfixes.entities.elytra.mixin.UTElytraLandingMixin (mixins.bugfixes.entities.elytra.json) [unknown-location]
        mod.acgaming.universaltweaks.bugfixes.entities.deathtime.mixin.UTDeathTimeMixin (mixins.bugfixes.entities.deathtime.json) [unknown-location]
        net.smileycorp.hordes.mixin.MixinEntityLivingBase (mixins.hordes.json) [unknown-location]
        mod.acgaming.universaltweaks.tweaks.misc.incurablepotions.mixin.UTIncurablePotionsMixin (mixins.tweaks.misc.incurablepotions.json) [unknown-location]
        revvilo.responsiveshields.mixin.MixinTicksConst (responsiveshields.mixin.json) [unknown-location]
        mod.acgaming.universaltweaks.bugfixes.entities.maxhealth.mixin.UTMaxHealthMixin (mixins.bugfixes.entities.maxhealth.json) [unknown-location]
        byoune.potiontweaker.mixin.MixinEntityLivingBase (potiontweaker.mixins.json) [unknown-location]
    net/minecraft/entity/Entity:
        meldexun.entityculling.mixin.MixinCullable (mixins.entityculling.json) [unknown-location]
        mod.acgaming.universaltweaks.bugfixes.entities.boundingbox.mixin.UTEntityBoundingBoxMixin (mixins.bugfixes.entities.boundingbox.json) [unknown-location]
        zone.rong.loliasm.common.crashes.mixins.EntityMixin (mixins.crashes.json) [unknown-location]
        meldexun.renderlib.mixin.caching.loadable.MixinEntity (mixins.renderlib.json) [unknown-location]
        mod.acgaming.universaltweaks.bugfixes.entities.desync.mixin.UTEntityMixin (mixins.bugfixes.entities.desync.json) [unknown-location]
        meldexun.renderlib.mixin.caching.boundingbox.MixinEntity (mixins.renderlib.json) [unknown-location]
        mod.acgaming.extrasounds.mixin.EntityMixin (extrasounds.server.mixins.json) [unknown-location]
        com.sonicether.soundphysics.mixin.vanilla.MixinEntity (soundphysics.vanilla.mixin.json) [unknown-location]
        mod.acgaming.universaltweaks.bugfixes.entities.suffocation.mixin.UTSuffocationMixin (mixins.bugfixes.entities.suffocation.json) [unknown-location]
        mod.acgaming.universaltweaks.bugfixes.entities.entityid.mixin.UTEntityIDMixin (mixins.bugfixes.entities.entityid.json) [unknown-location]
        meldexun.renderlib.mixin.caching.renderer.MixinEntity (mixins.renderlib.json) [unknown-location]
    net/minecraft/server/MinecraftServer:
        zone.rong.loliasm.common.priorities.mixins.MinecraftServerMixin (mixins.priorities.json) [unknown-location]
        ru.vidtu.ksyxis.mixins.MinecraftServerMixin (ksyxis.mixins.json) [unknown-location]
    net/minecraft/entity/EntityLivingBase:
        mod.acgaming.universaltweaks.tweaks.misc.armorcurve.mixin.UTValueUpdateMixin (mixins.tweaks.misc.armorcurve.json) [unknown-location]
        com.github.mikn.lava_walker.asm.mixin.EntityLivingBaseMixin (lava_walker.mixins.json) [unknown-location]
        mod.acgaming.universaltweaks.bugfixes.entities.elytra.mixin.UTElytraLandingMixin (mixins.bugfixes.entities.elytra.json) [unknown-location]
        mod.acgaming.universaltweaks.bugfixes.entities.deathtime.mixin.UTDeathTimeMixin (mixins.bugfixes.entities.deathtime.json) [unknown-location]
        net.smileycorp.hordes.mixin.MixinEntityLivingBase (mixins.hordes.json) [unknown-location]
        mod.acgaming.universaltweaks.tweaks.misc.incurablepotions.mixin.UTIncurablePotionsMixin (mixins.tweaks.misc.incurablepotions.json) [unknown-location]
        revvilo.responsiveshields.mixin.MixinTicksConst (responsiveshields.mixin.json) [unknown-location]
        mod.acgaming.universaltweaks.bugfixes.entities.maxhealth.mixin.UTMaxHealthMixin (mixins.bugfixes.entities.maxhealth.json) [unknown-location]
        byoune.potiontweaker.mixin.MixinEntityLivingBase (potiontweaker.mixins.json) [unknown-location]
    net/minecraft/entity/Entity:
        meldexun.entityculling.mixin.MixinCullable (mixins.entityculling.json) [unknown-location]
        mod.acgaming.universaltweaks.bugfixes.entities.boundingbox.mixin.UTEntityBoundingBoxMixin (mixins.bugfixes.entities.boundingbox.json) [unknown-location]
        zone.rong.loliasm.common.crashes.mixins.EntityMixin (mixins.crashes.json) [unknown-location]
        meldexun.renderlib.mixin.caching.loadable.MixinEntity (mixins.renderlib.json) [unknown-location]
        mod.acgaming.universaltweaks.bugfixes.entities.desync.mixin.UTEntityMixin (mixins.bugfixes.entities.desync.json) [unknown-location]
        meldexun.renderlib.mixin.caching.boundingbox.MixinEntity (mixins.renderlib.json) [unknown-location]
        mod.acgaming.extrasounds.mixin.EntityMixin (extrasounds.server.mixins.json) [unknown-location]
        com.sonicether.soundphysics.mixin.vanilla.MixinEntity (soundphysics.vanilla.mixin.json) [unknown-location]
        mod.acgaming.universaltweaks.bugfixes.entities.suffocation.mixin.UTSuffocationMixin (mixins.bugfixes.entities.suffocation.json) [unknown-location]
        mod.acgaming.universaltweaks.bugfixes.entities.entityid.mixin.UTEntityIDMixin (mixins.bugfixes.entities.entityid.json) [unknown-location]
        meldexun.renderlib.mixin.caching.renderer.MixinEntity (mixins.renderlib.json) [unknown-location]
    net/minecraft/world/WorldServer:
        mod.acgaming.universaltweaks.bugfixes.blocks.bed.mixin.UTSleepResetsWeatherMixin (mixins.bugfixes.blocks.bed.json) [unknown-location]
        rlmixins.mixin.vanilla.WorldServerMixin (mixins.rlmixins.core.entitytracker.json) [unknown-location]
        mod.acgaming.universaltweaks.bugfixes.entities.tracker.mixin.UTWorldServerMixin (mixins.bugfixes.entities.tracker.json) [unknown-location]
    net/minecraft/world/World:
        ru.vidtu.ksyxis.mixins.LevelMixin (ksyxis.mixins.json) [unknown-location]
        mod.acgaming.universaltweaks.bugfixes.entities.entitylists.mixin.UTWorldMixin (mixins.bugfixes.entities.entitylists.json) [unknown-location]
        meldexun.renderlib.mixin.MixinWorld (mixins.renderlib.json) [unknown-location]
        noobanidus.mods.lootr.mixins.MixinWorld (lootr.mixins.json) [unknown-location]
        meldexun.renderlib.mixin.caching.loadable.MixinWorld (mixins.renderlib.json) [unknown-location]
    net/minecraft/server/integrated/IntegratedServer:
        de.maxhenkel.voicechat.mixin.IntegratedServerMixin (voicechat.mixins.json) [unknown-location]
        zone.rong.loliasm.common.crashes.mixins.IntegratedServerMixin (mixins.crashes.json) [unknown-location]
    net/minecraft/server/MinecraftServer:
        zone.rong.loliasm.common.priorities.mixins.MinecraftServerMixin (mixins.priorities.json) [unknown-location]
        ru.vidtu.ksyxis.mixins.MinecraftServerMixin (ksyxis.mixins.json) [unknown-location]
    net/minecraft/world/World:
        ru.vidtu.ksyxis.mixins.LevelMixin (ksyxis.mixins.json) [unknown-location]
        mod.acgaming.universaltweaks.bugfixes.entities.entitylists.mixin.UTWorldMixin (mixins.bugfixes.entities.entitylists.json) [unknown-location]
        meldexun.renderlib.mixin.MixinWorld (mixins.renderlib.json) [unknown-location]
        noobanidus.mods.lootr.mixins.MixinWorld (lootr.mixins.json) [unknown-location]
        meldexun.renderlib.mixin.caching.loadable.MixinWorld (mixins.renderlib.json) [unknown-location]

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: betteranimalsplus:goat (its_meow.betteranimalsplus.common.entity.EntityGoat)
  Entity ID: 174
  Entity Name: Wild Goat
  Entity's Exact location: 250.71, 64.00, 10820.47
  Entity's Block location: World: (250,64,10820), Chunk: (at 10,4,4 in 15,676; contains blocks 240,0,10816 to 255,255,10831), Region: (0,21; contains chunks 0,672 to 31,703, blocks 0,0,10752 to 511,255,11263)
  Entity's Momentum: 0.00, -0.08, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {Pos:[250.70823443689218d,64.0d,10820.46649890602d],RelativeAABB:[-0.46000000834465027d,0.0d,-0.46000000834465027d,0.46000000834465027d,0.8049999475479126d,0.46000000834465027d],Motion:[0.0d,-0.0784000015258789d,0.0d],Rotation:[97.77002f,0.0f],FallDistance:0.0f,Fire:-1s,Air:300s,OnGround:1b,Dimension:0,Invulnerable:0b,PortalCooldown:0,UUIDMost:-6170790756274909527L,UUIDLeast:-8988321654368612720L,AABB:[250.24823442854753d,64.0d,10820.006498897676d,251.16823444523683d,64.80499994754791d,10820.926498914365d],UpdateBlocked:0b,Tags:["collective.checked"],ForgeData:{"mpr:checked":1b,"Potion Core - Health Fix":14.0f,"Potion Core - Jump Boost Updated":1b,hungryanimals.isInitialized:1b},ForgeCaps:{"llibrary:extendedentitydatacapability":{"mm:living":{freezeProgress:0.0f,frozenYaw:0.0f,frozenPitch:0.0f,frozenYawHead:0.0f,frozenRenderYawOffset:0.0f,frozenSwingProgress:0.0f,frozenLimbSwingAmount:0.0f,prevHasAI:0b,freezeDecayDelay:0}},"dsurround:data":{a:0b,f:0b},"hungryanimals:tamableanimal":-2.0d,"lilliputian:size":{scale:1.15f},"pyrotech:spear":{itemStacks:[],seed:0},"arcaneworld:rituallocation":{RitualDim:0,RitualX:0,RitualY:0,RitualZ:0},"hordes:hordespawn":"","lycanitesmobs:iextendedentity":{},"somanyenchantments:player_capabilities":{isResurrecting:0b,moralitasDamage:0.0d}},Health:14.0f,HurtTime:0s,HurtByTimestamp:0,DeathTime:0s,AbsorptionAmount:0.0f,Attributes:[{Name:"potioncore.projectileDamage",Base:1.0d},{Name:"potioncore.magicDamage",Base:1.0d},{Name:"potioncore.jumpHeight",Base:1.0d},{Name:"potioncore.damageResistance",Base:1.0d},{Name:"potioncore.magicShielding",Base:0.0d},{Name:"generic.maxHealth",Base:14.0d},{Name:"generic.knockbackResistance",Base:0.0d},{Name:"generic.movementSpeed",Base:0.5d,Modifiers:[]},{Name:"generic.armor",Base:0.0d},{Name:"generic.armorToughness",Base:0.0d},{Name:"forge.swimSpeed",Base:1.0d,Modifiers:[]},{Name:"generic.followRange",Base:16.0d,Modifiers:[{Name:"Random spawn bonus",Amount:0.10215792169117346d,Operation:1,UUIDMost:-820709868107904979L,UUIDLeast:-6206656262821022348L}]},{Name:"generic.attackDamage",Base:0.8d,Modifiers:[]}],FallFlying:0b,CanPickUpLoot:0b,PersistenceRequired:0b,ArmorItems:[{},{},{},{}],HandItems:[{},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],HandDropChances:[0.085f,0.085f],Leashed:0b,LeftHanded:0b,Age:0,ForcedAge:0,InLove:0,TypeNumber:3,AttackSync:0b}

-- Affected level --
  Level name: Temple of Avarice
  All players: 1 total; [EntityPlayerMP['Ski_'/1, l='Temple of Avarice', x=256.60, y=69.00, z=10778.96]]
  Chunk stats: ServerChunkCache: 529 Drop: 0
  Level seed: -804132085436318065
  Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
  Level generator options: 
  Level spawn location: World: (0,64,1000), Chunk: (at 0,4,8 in 0,62; contains blocks 0,0,992 to 15,255,1007), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
  Level time: 34000 game time, 3144 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 12618 (now: false), thunder time: 125503 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true

**Comment by Ski-z** [comment]
Basically, I can get the mod to function in every way with Minecraft or Animania mobs, but I can't get it to do the same with any other mobs. Will try to investigate further.

**Comment by Ski-z** [comment]
wait! It appears that the minimum requirements for adding a new mob is:

1. AI Json
2. Attributes Json

This prevents the crash. Closing now!
